# Generated by Django 3.0.6 on 2020-05-19 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('document_id', models.CharField(max_length=150, unique=True, verbose_name='numero do documento')),
                ('reg_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='matrícula')),
                ('slug', models.SlugField(default='', max_length=150, verbose_name='slug')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de proprietário',
                'verbose_name_plural': 'registros de proprietários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='marca / fabricante')),
                ('slug', models.SlugField(default='', max_length=150, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'marca / fabricante',
                'verbose_name_plural': 'marcas / fabricantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='modelo')),
                ('slug', models.SlugField(default='', max_length=150, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'modelo do veículo',
                'verbose_name_plural': 'modelos do veículos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=150, verbose_name='slug')),
                ('plate_num', models.CharField(max_length=7, unique=True, verbose_name='placa do veículo')),
                ('chassis_num', models.CharField(max_length=17, unique=True, verbose_name='chassis do veículo')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='data da criação do registro')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_admin.Brand', verbose_name='marca')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_admin.VehicleModel', verbose_name='modelo')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_admin.Partner', verbose_name='proprietário')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cadastro de veículo',
                'verbose_name_plural': 'cadastros de veículos',
                'ordering': ['user'],
            },
        ),
    ]
