# Generated by Django 3.1.1 on 2020-09-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'fabricante', 'verbose_name_plural': 'fabricantes'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'proprietário', 'verbose_name_plural': 'proprietários'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['user'], 'verbose_name': 'veículo', 'verbose_name_plural': 'veículos'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['name'], 'verbose_name': 'modelo', 'verbose_name_plural': 'modelos'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150, verbose_name='fabricante'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='reg_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='registro de matrícula'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_admin.brand', verbose_name='fabricante'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_num',
            field=models.CharField(max_length=17, unique=True, verbose_name='número de chassis'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_num',
            field=models.CharField(max_length=7, unique=True, verbose_name='numero da placa'),
        ),
    ]
